# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2025 Robert Gunnar Johnson Jr.
"""SSH config generation from keys.toml."""

from __future__ import annotations

from pathlib import Path

from loadout.display import is_macos
from loadout.secrets import SshKeyConfig
from loadout.ui import status_line, verbose_line

# Header comment for generated SSH config.
_HEADER = """\
# SSH config — generated by loadout
# Do not edit directly; changes will be overwritten on next build/init.
# To add custom settings, create ~/.ssh/config.local (included below).
"""


def generate_ssh_config(
    key_configs: list[SshKeyConfig],
    ssh_dir: Path,
) -> str:
    """Generate SSH config content from key configs.

    For each key, creates a Host entry with the appropriate IdentityFile.
    Keys with a ``host`` field get a dedicated Host block; the first key
    without an explicit host gets ``Host github.com``.

    Args:
        key_configs: SSH key configurations from keys.toml.
        ssh_dir: Path to the .ssh directory (for IdentityFile paths).

    Returns:
        The SSH config file content as a string.
    """
    lines = [_HEADER]

    # Global defaults
    lines.append("Host *")
    lines.append("    AddKeysToAgent yes")
    if is_macos():
        lines.append("    UseKeychain yes")
    lines.append("    IdentityAgent none")
    lines.append("")

    # Per-key Host entries
    default_host_assigned = False
    for key_config in key_configs:
        host = key_config.host
        host_name = key_config.host_name
        key_path = ssh_dir / key_config.filename

        if not host:
            if not default_host_assigned:
                host = "github.com"
                default_host_assigned = True
            else:
                host = f"github.com-{key_config.org}"
                host_name = host_name or "github.com"

        lines.append(f"Host {host}")
        if host_name:
            lines.append(f"    HostName {host_name}")
        lines.append(f"    IdentityFile {key_path}")
        lines.append("")

    # Include local overrides if they exist
    lines.append("# Local overrides (not managed by loadout)")
    lines.append("Include config.local")
    lines.append("")

    return "\n".join(lines)


def install_ssh_config(
    key_configs: list[SshKeyConfig],
    home: Path,
    *,
    dry_run: bool = False,
) -> None:
    """Generate and install ~/.ssh/config from key configs.

    Creates a backup of the existing config before overwriting.

    Args:
        key_configs: SSH key configurations from keys.toml.
        home: User's home directory.
        dry_run: If True, log what would happen without writing.
    """
    ssh_dir = home / ".ssh"
    config_path = ssh_dir / "config"

    if not key_configs:
        status_line(
            "[dim]\u23ed[/dim]",
            "SSH config",
            "no keys configured \u2014 skipping",
        )
        return

    content = generate_ssh_config(key_configs, ssh_dir)

    if dry_run:
        status_line(
            "[dim]\u25b6[/dim]",
            "SSH config",
            "would generate (dry run)",
        )
        verbose_line(content)
        return

    ssh_dir.mkdir(parents=True, exist_ok=True)

    # Backup existing config
    if config_path.exists():
        backup_path = config_path.with_suffix(".bak")
        config_path.rename(backup_path)
        status_line(
            "[dim]\u25b6[/dim]",
            "SSH config",
            f"backed up to {backup_path.name}",
        )

    config_path.write_text(content, encoding="utf-8")
    # SSH config must not be world-readable
    config_path.chmod(0o600)
    status_line("[green]\u2713[/green]", "SSH config", "generated")
